version: '3'

services:

  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root